-- Migration: add_directorate
-- Adds PENDING_DIRECTORATE/DIRECTORATE_APPROVED to OrderItemStatus + DIRECTORATE role

-- 1. Добавляем новые значения в enum OrderItemStatus (меняем default на PENDING_DIRECTORATE)
ALTER TABLE `OrderItem` MODIFY COLUMN `status` ENUM('PENDING_DIRECTORATE','DIRECTORATE_APPROVED','ACCEPTED','INVOICE_RECEIVED','INVOICE_PAID','SHIPPED','RECEIVED','SENT_TO_REQUESTER','ORDER_CONFIRMED') NOT NULL DEFAULT 'PENDING_DIRECTORATE';

-- 2. Добавляем новые значения в enum OrderItemStatus для statusLog
ALTER TABLE `OrderItemStatusLog` MODIFY COLUMN `oldStatus` ENUM('PENDING_DIRECTORATE','DIRECTORATE_APPROVED','ACCEPTED','INVOICE_RECEIVED','INVOICE_PAID','SHIPPED','RECEIVED','SENT_TO_REQUESTER','ORDER_CONFIRMED') NULL;

ALTER TABLE `OrderItemStatusLog` MODIFY COLUMN `newStatus` ENUM('PENDING_DIRECTORATE','DIRECTORATE_APPROVED','ACCEPTED','INVOICE_RECEIVED','INVOICE_PAID','SHIPPED','RECEIVED','SENT_TO_REQUESTER','ORDER_CONFIRMED') NOT NULL;

-- 3. Добавляем роль DIRECTORATE
ALTER TABLE `UserRole` MODIFY COLUMN `role` ENUM('ADMIN','HEAD_OF_SUPPLY','SUPPLY_DEPT','WAREHOUSE','REQUESTER','DIRECTORATE') NOT NULL;
